name: qrscan
description: A Plug-in for dart, which help you scanning barcode and qrcode with android device.
version: 0.2.21

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.5.1
  test_coverage: ^0.2.0